export class TPaymentHeader {
    companyCode: string;
    transId: string;
    title: string;
    remark: string;
    cusId: string;
    type: string;
    refTransId: string;
    reason: string;
    docDate: Date | string | null;
    docDueDate: Date | string | null;
    createdBy: string;
    createdOn: Date | string | null;
    modifiedBy: string;
    modifiedOn: Date | string | null; 
    status: string;
    customF1: string;
    customF2: string;
    customF3: string;
    customF4: string;
    customF5: string; 
    lines: TPaymentLine[];
}

export class TPaymentLine {
    paymentCode: string;
    companyCode: string;
    shortName: string;
    transId: string;
    lineId: string;
    storeId: string;
    totalAmt: number | null;
    receivedAmt: number | null;
    paidAmt: number | null;
    changeAmt: number | null;
    paymentMode: string;
    cardType: string;
    cardHolderName: string;
    cardNo: string;
    voucherBarCode: string;
    voucherSerial: string;
    createdBy: string;
    createdOn: Date | string | null;
    modifiedBy: string;
    modifiedOn: Date | string | null;
    status: string;
    chargableAmount: number | null;
    paymentDiscount: number | null;
    collectedAmount: number | null;
    refNumber: string;
    dataSource: string;
    currency: string;
    fcAmount: number | null;
    rate: number | null;
    shiftId: string;
    cardExpiryDate: Date | string | null;
    adjudicationCode: string;
    terminalId: string;
    authorizationDateTime: Date | string | null;
    roundingOff: number | null;
    fcRoundingOff: number | null;
    customF1: string;
    customF2: string;
    customF3: string;
    customF4: string;
    customF5: string;
    forfeitCode: string;
    forfeit: number | null;
    promoId: string;
    paymentType: string;
}