import { MBomline } from "../mbomline";
import { MItemSerial } from "../mitemserial";

export class ItemViewModel {
    keyId: string;  
    stt: number | null;
    itemCode: string;
    companyCode: string;
    productId: string;
    variantId: string; 
    capacityValue: number | null;
    itemGroupId: string;
    itemGroupName: string;
    salesTaxCode: string;
    salesTaxName: string;
    purchaseTaxCode: string;
    purchaseTaxName: string;
    itemName: string;
    itemDescription: string;
    itemCategory_1: string;
    itemCategory_2: string;
    itemCategory_3: string;
    foreignName: string;
    uomCode: string;
    uomName: string;
    imageUrl: string;
    imageLink: string;
    mcid: string;
    mcName: string;
    customField1: string;
    customField2: string;
    customField3: string;
    customField4: string;
    customField5: string;
    customField6: string;
    customField7: string;
    customField8: string;
    customField9: string;
    customField10: string;
    defaultPrice: number | null;
    isSerial: boolean | null;
    isBom: boolean | null;
    validFrom: Date | string | null;
    validTo: Date | string | null;
    barCode: string;
    qrCode: string;
    priceBeforeTax: number | null;
    priceAfterTax: number | null;
    slocId:  string;
    isVoucher:  boolean | null;
    rejectPayType: string; 
    salesTaxRate:number | null; 
    purchaseTaxRate:number | null;
    taxAmt?: number | null;
    baseLine: string;
    baseTransId: string;
    lines: MBomline[];
    serialLines: MItemSerial[];
    prefix: string;
    name: string;
    remark: string;
    phone: string;
    priceListId: string;
    custom1: string;
    custom2: string;
    custom3: string;
    custom4: string;
    custom5: string;
    returnable: boolean | null;
    voucherCollection: string="";
    isPriceTime:boolean | null=null;
    isWeightScaleItem:boolean | null=null;
    weightScaleBarcode:string | null=null;
    responseTime: Date | string | null;
    allowSalesNegative: boolean | null=null;
    mappingCode: string="";
    inventoryUomCode: string;
    inventoryUomName: string;
    isFixedQty: boolean | null=null;
    defaultFixedQty: number | null=null;
    priceListName: string="";  
    isHighLight: string="";  
}

export class ItemCheckModel {
    itemCode: string;
    slocId: string;
    uomCode: string;
    quantity: number;
    barcode: string;
    plu: string;
    customF1: string;
    customF2: string;
    customF3: string;
    customF4: string;
    customF5: string;
}