
import { MCustomer } from '../customer';
import { OrderLogModel } from '../orderlogModel';
import { TSalesHeader } from '../tsaleheader';
import { TSalesLine, TSalesLineSerial, TSalesPromo, TSalesStaff } from '../tsaleline';
import { TSalesPayment } from '../tsalepayment';
import { TSalesDelivery } from '../tsalesdelivery';
import { TSalesInvoice } from '../tsalesinvoice';
import { TSalesRedeemVoucher } from '../tsalesredeemvoucher';
import { TapTapVoucherDetails } from '../voucherdetail';

export class Order implements TSalesHeader {
    contractNo: string = '';
    isCanceled: string = '';
    remarkCustom1: string = '';
    totalAmount: number | null = null;
    amountChange: number | null = null;
    paymentDiscount: number | null = null;
    discountType: string = '';
    discountAmount: number | null = null;
    transId: string = '';
    orderId: string = '';
    companyCode: string = '';
    storeId: string = '';
    storeName: string = '';
    storeAddress: string = '';
    email: string = '';
    website: string = '';
    shiftId: string = '';
    cusId: string = '';
    cusIdentifier: string = '';
    rewardPoints: number | null = null;
    totalPayable: number | null = null;
    totalDiscountAmt: number | null = null;
    totalReceipt: number | null = null;
    totalTax: number | null = null;
    discountRate: number | null = null;
    createdOn: string | Date;
    createdBy: string = '';
    modifiedOn: string | Date;
    modifiedBy: string = '';
    status: string = '';
    remarks: string = '';
    salesPerson: string = '';
    salesPersonName: string = '';
    salesMode: string = '';
    refTransId: string = '';
    manualDiscount: string = '';
    salesType: string = '';
    dataSource: string = '';
    posType: string = '';
    customer: MCustomer;
    lines: TSalesLine[] = [];
    serialLines: TSalesLineSerial[] = [];
    promoLines: TSalesPromo[] = [];
    payments: TSalesPayment[] = [];
    contractPayments: TSalesPayment[] = [];
    deliveries: TSalesDelivery[] = [];
    voucherApply: TapTapVoucherDetails[] = [];
    vouchers: TSalesRedeemVoucher[] = [];
    invoice: TSalesInvoice;
    delivery: TSalesDelivery;
    phone: string = '';
    cusName: string = '';
    cusAddress: string = '';
    reason: string = '';
    collectedStatus: string = '';
    discountLine: number | null = null;
    bonusLine: number | null = null;
    startTime: Date | null = null;
    terminalId: string = '';
    currency: string = '';
    roundingOff: number | null = null; 
    shortOrderID: string = '';
    merchantId: string = '';
    syncMWIStatus: string = '';
    syncMWIDate: Date | null = null;
    syncMWIMsg: string = '';
    omsId: string = '';
    omsStatus: string = '';
    chanel: string = '';
    cusGrpId: string = '';
    promoId: string = '';
    approvalId:  string='';
    totalQty: number | null = null;
    companyName: string = '';
    companyPhone: string = '';
    storePhone: string = ''; 
    expiryDate: Date | null = null;
    docDate: Date | string | null;
    customF1: string= '';
    customF2: string= '';
    customF3: string= '';
    customF4: string= '';
    customF5: string= '';
    luckyNo: string= '';
    logs: OrderLogModel[]= [];
    printRemarks: string= '';
    printName: string;
    isDrawer: string;
    isPrint: string;
    otherTerminalId:  string='';
    hasVoucher: boolean | null = null;
    pinSerialDisplayUpper:  string='';
    staffs:  TSalesStaff[] =  [];
    checkOutOn:  string='';
    salesChanel:string;
    tempTransId: string= '';
    loyaltyName: string= '';
}
