export interface TProductionOrderHeader {
    purchaseId: string;
    companyCode: string;
    storeId: string;
    storeName: string;
    type: string;
    sapStatus: string;
    productNo: string;
    description: string;
    uomCode: string;
    uomName: string;
    quantity: number | null;
    warehouseCode: string;
    priority: number | null;
    routingDateCalculation: string;
    isProductItem: boolean | null;
    sapNo: string;
    orderDate: string | null;
    docDate: string | null;
    docDueDate: string | null;
    origin: string;
    linkedTo: string;
    linkedOrder: string;
    customer: string;
    distrRule: string;
    project: string;
    customField1: string;
    customField2: string;
    customField3: string;
    customField4: string;
    customField5: string;
    createdOn: string | null;
    createdBy: string;
    comment: string;
    isCanceled: string;
    status: string;
    modifiedBy: string;
    modifiedOn: string | null;
    docEntry: string;

}

export interface TProductionOrderLine {
    purchaseId: string;
    companyCode: string;
    lineId: string;
    slocId: string;
    itemCode: string;
    description: string;
    type: string;
    barCode: string;
    uomCode: string;
    uomName: string;
    sapNo: string;
    baseQty: number | null;
    baseRatio: number | null;
    addtitionalQty: number | null;
    plannedQty: number | null;
    issueId: number | null;
    available: number | null;
    wareHouse: string;
    issueMethod: string;
    startDate: string | null;
    endDate: string | null;
    openQty: number | null;
    inStock: number | null;
    ordered: string;
    committed: string;
    rowNo: string;
    wIPAccount: string;
    phongBan: string;
    cuaHang: string;
    kenhBanHang: string;
    project: string;
    productionTime: string;
    additionalTime: string;
    runTime: string;
    requiredDay: string;
    waitingDay: string;
    totalDay: string;
    resourceAllocation: string;
    qtyInWhse: number | null;
    committedQtyInWhse: number | null;
    orderedQtyInWhse: number | null;
    routeSequence: number | null;
    status: string;
    caculationProportion: number | null;
    procurementDoc: string;
    allowProcurmtDoc: string;
    customField1: string;
    customField2: string;
    customField3: string;
    customField4: string;
    customField5: string;
    customField6: string;
    customField7: string;
    customField8: string;
    customField9: string;
    customField10: string;
}

